### ISSUE TITLE
dynamic feature extraction according to the feature xml file

### ISSUE THREAD

**Issue by hala-maghout** [lspecia/quest#17] opened 2013-02-22 14:45 UTC
POSprocessors are always run in the runBB() method without checking whether POS-based features are incorporated in the features xml file. I think feature calculation and processing should be conditioned on the availability of the related features in the features xml file.

**Comment by lefterav** [comment] 2013-02-22 14:53
Hi Hala, thanks for pointing this out. I think this is a duplicate of issue https://github.com/lspecia/quest/issues/5 . If so, we should close this issue so that the discussion keeps going there

**Closed as completed** 2013-02-26 10:32 UTC
Labels: duplicate
